name: Deploy Telegram Bot

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy with Docker Compose
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_IDS: ${{ secrets.ADMIN_IDS }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            cd /home/nedanaec/projects/DY_MakerBank_bot
            
            git pull

            printf "BOT_TOKEN=%s\n" "$BOT_TOKEN" > .env
            printf "ADMIN_IDS=%s\n" "$ADMIN_IDS" >> .env


            docker-compose up -d --build
          EOF